name: Game Simulation Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight

jobs:
  simulate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Run non-interactive game simulation
      run: |
        # Set non-interactive test mode for LLM providers
        export ROMAN_SENATE_TEST_MODE=true
        # Run a complete game simulation
        python -m roman_senate.cli simulate --senators 5 --debate-rounds 2 --topics 1 --non-interactive
    
    - name: Archive simulation logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: simulation-logs
        path: |
          logs/
          data/saves/