name: Python Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to test'
        required: false
        default: '3.10'
        type: choice
        options:
        - '3.9'
        - '3.10'
        - '3.11'
      run-all:
        description: 'Run all tests or just a specific module'
        required: false
        default: true
        type: boolean
      test-path:
        description: 'Test path to run (if run-all is false)'
        required: false
        default: 'tests/'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ github.event_name == 'workflow_dispatch' && fromJSON(format('["{0}"]', github.event.inputs.python-version)) || fromJSON('["3.9", "3.10", "3.11"]') }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        pip install -e .
    
    - name: Test with pytest
      run: |
        pytest